✨ Redo config system with TOML
Fabulously-Optimized/vanilla-installer pull request #69
Opened 2023-01-22 21:30 UTC by osfanbuff63

Fixes #60

Somewhat tested, but more testing would be appreciated.

2023-01-26 08:26 UTC, tuxinal commented
Looks good to me, except the fact that gui crashes. I fixed the crash and tried to upload the .patch file here but github doesn't let me - _despite listing .patch files as a valid file to upload_ - 
Besides that it works as expected

2023-02-01 15:42 UTC, tuxinal requested changes
Looks good to me besides these issues
the theme is stuck on dark mode and the platform import in gui.py got reverted in the last merge commit

2023-02-01 15:42 UTC, tuxinal commented on vanilla_installer/theme.py
> +    is_dark(is_dark() == "dark")
```suggestion
    is_dark(is_dark() != "dark")
```

2023-02-01 15:42 UTC, tuxinal commented on vanilla_installer/theme.py
> +    return dark_theme if is_dark("dark") else light_theme
```suggestion
    return dark_theme if is_dark() == "dark" else light_theme
```

2023-02-01 15:42 UTC, tuxinal commented on vanilla_installer/gui.py
this import got reverted by the main branch merge in the previous commit
```suggestion
import platform
```

2023-02-01 15:42 UTC, tuxinal commented on vanilla_installer/gui.py
>  FONT_FILE = pathlib.Path("data/font.txt").resolve()
not necessary anymore
```suggestion
```

2023-02-01 15:50 UTC, osfanbuff63 commented on vanilla_installer/theme.py
> +    is_dark(is_dark() == "dark")
:ioa: lol

2023-02-07 22:37 UTC, merged